// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AllottedDetail: typeof import('./src/components/AllottedDetail.vue')['default']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectDetail: typeof import('./src/components/ProjectDetail.vue')['default']
    ProjectFooter: typeof import('./src/components/ProjectFooter.vue')['default']
  }
}

export { }
