// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AllottedDetail: typeof import('./src/components/AllottedDetail.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    ManageProfile: typeof import('./src/components/ManageProfile.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectDetail: typeof import('./src/components/ProjectDetail.vue')['default']
    ProjectFooter: typeof import('./src/components/ProjectFooter.vue')['default']
  }
}

export { }
